---
- name: Set Up Server
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Set timezone to {{ LOCAL_TIMEZONE }}
      timezone:
        name: "{{ LOCAL_TIMEZONE }}"

    - name: Set up a unique hostname
      hostname: name={{ LOCAL_HOSTNAME }}

    - name: Add PHP repository
      apt_repository:
        repo: ppa:ondrej/php
        state: present
        filename: php

    - name: Add Nginx repository
      apt_repository:
        repo: ppa:nginx/stable
        state: present
        filename: nginx

    - name: Add Redis repository
      apt_repository:
        repo: ppa:chris-lea/redis-server
        state: present
        filename: redis

    - name: Add MySQL Repository
      apt_repository:
        repo: "deb http://repo.mysql.com/apt/ubuntu focal mysql-8.0"
        state: present
        filename: mysql
      when: INSTALL_MYSQL|bool == true

    - name: APT is updated/upgraded
      apt:
        upgrade: "yes"
        cache_valid_time: 3600

    - name: MySQL server installed
      apt:
        name: mysql-server
        state: latest
      when: INSTALL_MYSQL|bool == true

    - name: Necessary packages are installed
      apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - aptitude
        - vim
        - git
        - curl
        - htop
        - unzip
        - cifs-utils
        - unrar
        - zip
        - p7zip-full
        - p7zip-rar
        - sharutils
        - rar
        - whois
        - traceroute
        - nmap
        - mc
        - neofetch
        - apt-transport-https
        - ethtool
        - net-tools
        - dos2unix
        - telnet
        - python3-mysqldb
        - php{{ PHP_VERSION }}-bz2
        - php{{ PHP_VERSION }}-cgi
        - php{{ PHP_VERSION }}-cli
        - php{{ PHP_VERSION }}-common
        - php{{ PHP_VERSION }}-curl
        - php{{ PHP_VERSION }}-dev
        - php{{ PHP_VERSION }}-enchant
        - php{{ PHP_VERSION }}-fpm
        - php{{ PHP_VERSION }}-gd
        - php{{ PHP_VERSION }}-gmp
        - php{{ PHP_VERSION }}-imap
        - php{{ PHP_VERSION }}-intl
        - php{{ PHP_VERSION }}-json
        - php{{ PHP_VERSION }}-ldap
        - php{{ PHP_VERSION }}-mysql
        - php{{ PHP_VERSION }}-odbc
        - php{{ PHP_VERSION }}-opcache
        - php{{ PHP_VERSION }}-pgsql
        - php{{ PHP_VERSION }}-phpdbg
        - php{{ PHP_VERSION }}-pspell
        - php{{ PHP_VERSION }}-readline
        - php{{ PHP_VERSION }}-sybase
        - php{{ PHP_VERSION }}-tidy
        - php{{ PHP_VERSION }}-xmlrpc
        - php{{ PHP_VERSION }}-xsl
        - php{{ PHP_VERSION }}-sqlite3
        - php{{ PHP_VERSION }}-mbstring
        - php{{ PHP_VERSION }}-bcmath
        - php{{ PHP_VERSION }}-soap
        - php{{ PHP_VERSION }}-zip
        - php-xdebug
        - php-redis
        - php-igbinary
        - php-imagick
        - nginx
        - redis-server
        - supervisor
        - python3-pip
        - python3-certbot-nginx
        - python3-certbot-dns-*

    - name: Supervisor service is enabled
      service:
        name: supervisor
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Download composer installer
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-installer

    - name: Install composer
      shell: cat /tmp/composer-installer | php && mv composer.phar /usr/bin/composer

#    - name: Download Gitlab Runner installer
#      get_url:
#        url: https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh
#        dest: /tmp/gitlab-runner-installer
#
#    - name: Install Gitlab Runner
#      shell: cat /tmp/gitlab-runner-installer | bash

    - name: Make composer executable
      file:
        path: /usr/bin/composer
        mode: a+x
        state: file

    - name: Install NVM
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
      args:
        creates: "/home/{{ DEPLOYER_USER }}/.nvm/nvm.sh"
      when: INSTALL_NVM|bool == true

    - name: PHP Config File deployed
      template:
        src: php/00-default.ini.j2
        dest: /etc/php/{{ PHP_VERSION }}/fpm/conf.d/00-default.ini

    - name: PHP service is enabled
      service:
        name: php{{ PHP_VERSION }}-fpm
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Nginx service is enabled
      service:
        name: nginx
        enabled: yes
        state: started
        daemon_reload: yes

    - name: MySQL service is enabled
      service:
        name: mysql
        enabled: yes
        state: started
        daemon_reload: yes
      when: INSTALL_MYSQL|bool == true

    - name: Redis service is enabled
      service:
        name: redis-server
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Create a database
      mysql_db:
        name={{ MYSQL_DB }}
        state=present
      when: INSTALL_MYSQL|bool == true

    - name: Create a new database user
      mysql_user:
        name={{ MYSQL_USER }}
        password={{ MYSQL_PASSWORD }}
        priv=*.*:ALL
        host=%
        state=present
      when: INSTALL_MYSQL|bool == true

    - name: MySQL server make available remotely
      lineinfile:
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        state: present
        line: 'bind-address    = *'
      when: INSTALL_MYSQL|bool == true

    - name: MySQL service is restarted
      service:
        name: mysql
        enabled: yes
        state: restarted
        daemon_reload: yes
      when: INSTALL_MYSQL|bool == true

    - name: Make sure we have a 'admins' group
      group:
        name: admins
        state: present

    - name: Make sure we have a deployer user
      user:
        name: "{{ DEPLOYER_USER }}"
        state: present

    - name: Allow 'admins' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%admins'
        line: '%admins ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Add sudoers users to admins group
      user:
        name={{ DEPLOYER_USER }}
        groups=admins,www-data
        shell=/bin/bash
        append=yes
        state=present
        createhome=yes
        generate_ssh_key=yes

    - name: Set up authorized keys for the {{ DEPLOYER_USER }} user
      authorized_key: user={{ DEPLOYER_USER }} key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub

    - name: Creates server directory
      file:
        path: /var/www/{{ LOCAL_FQDN_NAME }}/current/public
        state: directory
        owner: www-data
        group: www-data
        mode: 0775
        recurse: yes

    - name: Creates server logs directory
      file:
        path: /var/www/{{ LOCAL_FQDN_NAME }}/logs
        state: directory
        mode: 0777

    - name: Copy the nginx config file and restart nginx
      synchronize:
        src: nginx/snippets/
        dest: /etc/nginx/snippets/

    - name: Copy the nginx config file and restart nginx
      template:
        src=nginx/site.conf.j2
        dest=/etc/nginx/sites-available/{{ LOCAL_FQDN_NAME }}.conf

    - name: Create symlink
      file:
        src: /etc/nginx/sites-available/{{ LOCAL_FQDN_NAME }}.conf
        dest: /etc/nginx/sites-enabled/{{ LOCAL_FQDN_NAME }}.conf
        state: link

    - name: Nginx service is reloaded
      service:
        name: nginx
        state: reloaded

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes





