[servers]
server1

[servers:vars]
ansible_ssh_host = 217.147.233.43
ansible_ssh_user = avto
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_ssh_private_key_file = ~/.ssh/id_rsa
ansible_python_interpreter = /usr/bin/python3
LOCAL_HOSTNAME = 'erp-production'
LOCAL_FQDN_NAME = 'erp.iliauni.edu.ge'
LOCAL_TIMEZONE = 'Asia/Tbilisi'
PHP_VERSION = '7.4'
MYSQL_USER = 'erp'
MYSQL_PASSWORD = 'uSG8vd7rXeM5qcKjW1fViH3C?kB~)20t'
MYSQL_DB = 'erp_production'
DEPLOYER_USER = 'deployer'
INSTALL_MYSQL=false
INSTALL_NVM=true