---
- name: Set Up PPTP VPN
  hosts: all
  become: true
  vars:
    pptp_username: vpnuser
    pptp_password: 123456
  tasks:
    - name: APT is updated/upgraded
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600

    - name: Necessary packages are installed
      apt: pkg={{ item }} state=latest
      with_items:
        - vim
        - git
        - curl
        - htop
        - unzip
        - cifs-utils
        - unrar
        - zip
        - p7zip-full
        - p7zip-rar
        - sharutils
        - rar
        - whois
        - traceroute
        - nmap
        - mc
        - apt-transport-https
        - ethtool
        - net-tools
        - dos2unix
        - liblz4-tool
        - pptpd
        - iptables-persistent

    - name: Local and remote ip specified in pptpd.conf
      lineinfile:
        path: /etc/pptpd.conf
        line: "{{ item }}"
      with_items:
        - localip 192.168.0.1
        - remoteip 192.168.0.100-200
      notify:
        - restart pptpd

    - name: Comment out require-mppe-128
      replace:
        dest: /etc/ppp/pptpd-options
        regexp: '^require-mppe-128'
        replace: '#require-mppe-128'

    - name: Users added in chap-secrets
      lineinfile:
        path: /etc/ppp/chap-secrets
        line: "{{ pptp_username }} pptpd {{ pptp_password }} *"

    - name: dns added to pptpd-options
      lineinfile:
        path: /etc/ppp/pptpd-options
        line: "{{ item }}"
      with_items:
        - ms-dns 8.8.8.8
        - ms-dns 8.8.4.4
      notify:
        - restart pptpd

    - name: Forwarding is set up
      sysctl: name=net.ipv4.ip_forward value=1 state=present reload=yes

    - name: NAT rule is added for iptables
      iptables:
        comment: Allow PPTP forwarding
        action: append
        table: nat
        chain: POSTROUTING
        out_interface: eth0
        jump: MASQUERADE
      notify:
        - save iptables

    - name: PPTPD service is enabled
      service:
        name: pptpd
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Netfilter Persistent service is enabled
      service:
        name: netfilter-persistent
        enabled: yes
        state: started
        daemon_reload: yes

  handlers:
    - name: save iptables
      command: bash -c "iptables-save > /etc/iptables/rules.v4"

    - name: restart pptpd
      service:
        name: pptpd
        state: restarted
